# Generated by Django 3.0.6 on 2020-05-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20200520_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.ManyToManyField(to='users.Address'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='pages',
            field=models.ManyToManyField(to='users.Pages'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.ManyToManyField(to='users.UserRoles'),
        ),
    ]
