# Generated by Django 3.0.6 on 2020-06-29 07:18

from django.db import migrations, models
import django.db.models.deletion
from accounts.logics import addDefaultGroups
from accounts.logics import addDefaultAccounts

def defaultGroups(apps,schema_editor):

    addDefaultGroups()

def defaultAccounts(apps,schema_editor):

    addDefaultAccounts()



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAccountGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.TblAccountGroups')),
            ],
        ),

        migrations.RunPython(defaultGroups),

        migrations.CreateModel(
            name='TblAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.TblAccountGroups')),
            ],
        ),

        migrations.RunPython(defaultAccounts),

        migrations.CreateModel(
            name='TblGeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=100)),
                ('db_amt', models.FloatField(default=0)),
                ('cr_amt', models.FloatField(default=0)),
                ('discription', models.CharField(blank=True, max_length=300, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.TblAccounts')),
            ],
        ),
    ]
