# Generated by Django 3.0.6 on 2020-06-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shops', '0002_auto_20200619_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TblItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('parent', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('rate', models.FloatField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='items.TblBrand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.TblItemCategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.ShopDetails')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='items.TblItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TblInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('v_type', models.CharField(max_length=50)),
                ('ref_no', models.IntegerField()),
                ('in_qty', models.FloatField(default=0)),
                ('out_qty', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.TblItems')),
            ],
        ),
    ]
