# Generated by Django 3.0.6 on 2020-06-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('staffs', models.ManyToManyField(related_name='staffs', to=settings.AUTH_USER_MODEL)),
                ('super_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='super_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('Longitude', models.CharField(max_length=100, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shops.ShopDetails')),
            ],
        ),
    ]
