# Generated by Django 3.0.6 on 2020-06-25 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def addDefaultStatus(apps, schema_editor):

    TblStatus = apps.get_model("orders", "TblStatus")
    db_alias = schema_editor.connection.alias

    lst = ["pending", "approved", "declained", "shipped", "out for delivery", "delivered", "cancelled"]

    for i in lst:
        if TblStatus.objects.using(db_alias).filter(name= i).count() == 0:
            obj_status = TblStatus(name= i)
            obj_status.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_address_user'),
        ('payments', '0001_initial'),
        ('Shops', '0002_auto_20200619_0845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_tblbrand_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.FloatField(default=0)),
                ('is_new', models.BooleanField(default=True)),
                ('ref_no', models.CharField(max_length=100)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Address')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.TblPayments')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shops.ShopDetails')),
            ],
        ),
        migrations.CreateModel(
            name='TblStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),

        migrations.RunPython(addDefaultStatus),

        migrations.CreateModel(
            name='TblStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.TblOrderDetails')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.TblStatus')),
            ],
        ),
        migrations.AddField(
            model_name='tblorderdetails',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.TblStatus'),
        ),
        migrations.AddField(
            model_name='tblorderdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TblIssuedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('disc_perc', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('net_amt', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.TblItems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.TblOrderDetails')),
            ],
        ),
    ]
